### ISSUE TITLE
Apps on the website don't work any more

### ISSUE THREAD

**Issue by constantinpape** [bioimage-io/archive.bioimage.io#242]
Maybe related to recent changes in https://github.com/bioimage-io/collection-bioimage-io? See the video for details:

https://user-images.githubusercontent.com/4263537/155891939-76b78b13-fc00-449a-a418-b36ed17c58d0.mp4

**Comment by constantinpape** [comment]
@oeway could you have a look into this?

**Comment by oeway** [comment]
Hi, I checked this roughly, there are a couple of places needed to be changed to reflect the changes of id matching, but I am lack of bandwidth at the moment. 


@FynnBe  I think the easiest way to make it work is to change the collection repo such that we make a copy of the latest RDF with the short id (without version id). Would that be easy to do?

I will implement the versioned list later, but it's really important to fix the website now considering it's in production.

**Comment by FynnBe** [comment]
> Hi, I checked this roughly, there are a couple of places needed to be changed to reflect the changes of id matching, but I am lack of bandwidth at the moment.
> 
> @FynnBe I think the easiest way to make it work is to change the collection repo such that we make a copy of the latest RDF with the short id (without version id). Would that be easy to do?
> 
> I will implement the versioned list later, but it's really important to fix the website now considering it's in production.

That would be easy to do, but every latest version would appear twice... ?

**Comment by oeway** [comment]
> That would be easy to do, but every latest version would appear twice... ?

I think we should not list all the versions for the same RDF in the summary RDF file, only the latest version. The versions should be pulled when the user click an item .

Edit: @FynnBe Could you add a `versions` field in the summary field in the generated rdf.json with a list of version ids? I can then take it from there to display the list.

**Comment by oeway** [comment]
@FynnBe Could you give it a try to fix this issue too? Note that this is quite urgent, since no one can download the models from the website at the moment. I now wonder whether the same issues exists on your forked collection repo, otherwise we should have found out this issue before merging, it seems I tested on your branch once.

**Comment by FynnBe** [comment]
I added 'previous_versions' to the collection.json entries (collection.json == rdf.json; I just started the process of renaming it collection.json as this file is not a valid RDF... but I will keep a 'rdf.json' copy around for compatibility) 
https://github.com/bioimage-io/collection-bioimage-io/pull/307

We actually already limit the collection to the latest versions of resources

**Comment by FynnBe** [comment]
`previous_versions` now deployed, e.g. https://github.com/bioimage-io/collection-bioimage-io/blob/8ad80d986cc07d56f33dd9d7d73e93b9f8753385/collection.json#L2697-L2699

**Comment by oeway** [comment]
@FynnBe Thanks for looking into this!

> I added 'previous_versions' to the collection.json entries (collection.json == rdf.json; I just started the process of renaming it collection.json as this file is not a valid RDF... but I will keep a 'rdf.json' copy around for compatibility)

Why not? I think it's actually a valid RDF with `type: collection`, that's the whole point of changing it into a collection in our previous discussions.

We need to be careful about these changes, the rdf url maybe already used by other people, e.g. deepimagej or deepicy, I have been telling people this file in the past. If not absolutely needed right now, I would postpone it until we checked with others.

> We actually already limit the collection to the latest versions of resources

Good, then it should be easy to change the id to the short version for the copy of the latest RDF?

**Comment by oeway** [comment]
> `previous_versions` now deployed, e.g. https://github.com/bioimage-io/collection-bioimage-io/blob/8ad80d986cc07d56f33dd9d7d73e93b9f8753385/collection.json#L2697-L2699

I see the changes now! However, this is not exactly what we need to restore the function on the website. We also need to change the id in the summary into the short version (e.g. from `"id": "10.5281/zenodo.5749843/5888237"` to `"id": "10.5281/zenodo.5749843"`). So this means that in the summary, we only show the short resource id.  And since we have the correct absolute rdf_source url, it will map to the latest version. We should retain the functions on the website after this change.

If we do that, I would rather not call it `previous_versions` but only `versions` to include a list of all the version numbers including the current latest version id. To save some bytes in the summary file, I would only show the version id (e.g. `["5888237", "5888232"]`).

**Comment by FynnBe** [comment]
alright, this feels very monkeypatchy. We then need to make sure to still display the full version id on the website and not just the resource id or do we go back to just using the resource id without the specific version???

**Comment by FynnBe** [comment]
> > `previous_versions` now deployed, e.g. https://github.com/bioimage-io/collection-bioimage-io/blob/8ad80d986cc07d56f33dd9d7d73e93b9f8753385/collection.json#L2697-L2699
> 
> I see the changes now! However, this is not exactly what we need to restore the function on the website. We also need to change the id in the summary into the short version (e.g. from `"id": "10.5281/zenodo.5749843/5888237"` to `"id": "10.5281/zenodo.5749843"`). So this means that in the summary, we only show the short resource id. And since we have the correct absolute rdf_source url, it will map to the latest version. We should retain the functions on the website after this change.
> 
> If we do that, I would rather not call it `previous_versions` but only `versions` to include a list of all the version numbers including the current latest version id. To save some bytes in the summary file, I would only show the version id (e.g. `["5888237", "5888232"]`).

deployed now: https://github.com/bioimage-io/collection-bioimage-io/blob/012acff58cdae2b68170c782731c7d430a92bbd3/collection.json#L2910-L2913

**Comment by oeway** [comment]
> alright, this feels very monkeypatchy. 

Our top priority is to retain the function of the website so users can download models normally, I will do whatever needed to quickly restore it. 

Plus, I am not sure if this is monkey patch, the summary can be interpreted as the general summary for a resource (not only the latest version), and that's why we have a full list of `versions`.

> We then need to make sure to still display the full version id on the website and not just the resource id or do we go back to just using the resource id without the specific version???

We need to go back to the short resource id to retain the apps for downloading models.

Version list is not implemented on the website yet, so it doesn't really mater for the moment. After we retain the functionality on the website, I suggest we can develop the version list via your fork of the collection repo + a PR preview of the website.

**Comment by oeway** [comment]
FYI: I have implemented the changes above and restore the the changes to the website.

The apps should work again after merging #249

**Comment by FynnBe** [comment]
> Plus, I am not sure if this is monkey patch, the summary can be interpreted as the general summary for a resource (not only the latest version), and that's why we have a full list of versions.

Yes, on second thought this is totally fine

> Version list is not implemented on the website yet, so it doesn't really mater for the moment. After we retain the functionality on the website, I suggest we can develop the version list via your fork of the collection repo + a PR preview of the website.

sounds good 👍
