### ISSUE TITLE
Cover images not shown in model cards

### ISSUE THREAD

**Issue by constantinpape** [bioimage-io/archive.bioimage.io#258]
Currently most of the cover images are not shown.

![image](https://user-images.githubusercontent.com/4263537/161974178-773d0d1c-55be-4d3a-b741-db64be66630f.png)

**Comment by oeway** [comment]
I just checked, it's because of some changes in the collection repo. 

This cover URL for example: https://raw.githubusercontent.com/deepimagej/models/master/frunet_sev.jpg does not exists.

Edit: And the Zenodo ones are also not working: https://zenodo.org/api/files/c8028ef3-de08-459c-b88a-2f0bfd11485b/diagram-of-InceptionV3.png

@FynnBe Any idea? If you didn't change the way we obtain the cover URL, then it's a Zenodo issue.

**Comment by oeway** [comment]
The downloads are also failing, could you guys try to download a model from zenodo, either through the downloader or zenodo directly?

It appears that the zenodo storage server is down at the moment.

**Comment by constantinpape** [comment]
Yes, the downloader is also not working for me. So maybe it's a zenodo problem?

**Comment by FynnBe** [comment]
> This cover URL for example: https://raw.githubusercontent.com/deepimagej/models/master/frunet_sev.jpg does not exists.

The deepimagej collection has known issues; this might be unrelated

The majority of cover images seems to be back and I now was able to download a model, but after successful download I got an obscure error message anyway: 
![image](https://user-images.githubusercontent.com/15139589/162035633-438a58a5-31f1-4000-b852-182a81e606ac.png)
the downloaded package contains: 
![image](https://user-images.githubusercontent.com/15139589/162035745-8b5b0fac-bef5-4c46-b077-6b3e56d3b027.png)

(I downloaded the "ilastik" variant)

**Comment by FynnBe** [comment]
btw, the hover text of the download icon is now "Imjoy Collection"
![image](https://user-images.githubusercontent.com/15139589/162036656-3b59a0ae-e045-4867-822d-a65e1de66c61.png)

I don't think that is particularly intuitive

**Comment by oeway** [comment]
> btw, the hover text of the download icon is now "Imjoy Collection"
> 
> ![image](https://user-images.githubusercontent.com/15139589/162036656-3b59a0ae-e045-4867-822d-a65e1de66c61.png)
> 
> 
> 
> I don't think that is particularly intuitive

I didn't change anything, it's likely caused by some changes in the collection repo. Somehow the bioengine app name is not passed along to the RDF and it used the collection name.

**Comment by oeway** [comment]
> The majority of cover images seems to be back and I now was able to download a model, but after successful download I got an obscure error message anyway: 
> 
> ![image](https://user-images.githubusercontent.com/15139589/162035633-438a58a5-31f1-4000-b852-182a81e606ac.png)
> 
> the downloaded package contains: 
> 
> ![image](https://user-images.githubusercontent.com/15139589/162035745-8b5b0fac-bef5-4c46-b077-6b3e56d3b027.png)
> 
> 
> 
> (I downloaded the "ilastik" variant)

Well, I think this is exactly what I was trying to say before in another issue when you want to change from relative URL to absolute URL, we human programmers always miss something even if we are very sure and we can test it but we always can always miss some test cases ;)


In this particular case, the issue  is from "dependencies: conda:https://...". And in the downloader code we have: https://github.com/ilastik/bioimage-io-resources/blob/ec271538c633b517d1af95569a77c87104d4c914/src/ilastik-app.imjoy.html#L149

Maybe you should go back to that issue and make sure you go through that list? I already forgot which issue or which are the things might be affected. @FynnBe

**Comment by FynnBe** [comment]
> I didn't change anything, it's likely caused by some changes in the collection repo. Somehow the bioengine app name is not passed along to the RDF and it used the collection name.

Yes, this is indeed caused by the collection repo. The problem is that in the [imjoy collection](https://raw.githubusercontent.com/imjoy-team/bioimage-io-models/master/manifest.bioimage.io.yaml) according to the current collection RDF spec a name is given (inherited from root). In the collection we do resolve the imjoy plugin data, but then we overwrite it with the data from the spec. I think this preference of the data in the bioimageio collection over the data in the referenced imjoy plugin is desirable. So I suggest to update the imjoy collection: https://github.com/imjoy-team/bioimage-io-models/pull/7

**Comment by FynnBe** [comment]
> In this particular case, the issue is from "dependencies: conda:https://...". And in the downloader code we have:

I see that this causes the current issue, but it should be a URL here, as the dependency file is hosted on zenodo and not on our collection gh-pages branch where we host the updated rdf. We should therefore update the downloader to correctly resolve the dependency file...

Probably I'm missing something as I have no clue which issue and what list you are referencing 😆

**Comment by oeway** [comment]
> In the collection we do resolve the imjoy plugin data, but then we overwrite it with the data from the spec. 

I am a bit confused about how it is being implemented now. I think the correct behavior should be first resolve the plugin data, then treat the resolved RDF as spec, so we don't overwrite it from collection. The resolved fields should have higher priority than the ones in collection. Is that possible?

**Comment by oeway** [comment]
> > In this particular case, the issue is from "dependencies: conda:https://...". And in the downloader code we have:
> 
> 
> 
> I see that this causes the current issue, but it should be a URL here, as the dependency file is hosted on zenodo and not on our collection gh-pages branch where we host the updated rdf. We should therefore update the downloader to correctly resolve the dependency file...
> 
> 
> 
> Probably I'm missing something as I have no clue which issue and what list you are referencing 😆 

Yes, it should be addressed in all the downloaders, and it suppose to be fixed here: https://github.com/bioimage-io/collection-bioimage-io/issues/310#issuecomment-1056710747

( this is the issue I am referring too )

**Comment by FynnBe** [comment]
> Is that possible?

yes, but:
I use bioimageio.spec to load the partner collections. (I think this is important for consistency)
Atm the `imjoy_plugin_parser` only lives in the collection repo; bioimageio.spec is unaware of it.
For what you want we need to add the `imjoy_plugin_parser` to bioimageio.spec, i.e. make it an official part of the spec.

I think this is out of hand. Maybe we can deploy the `imjoy_plugin_parser` in https://github.com/imjoy-team/bioimage-io-models instead and generate the imjoy collection from a template with this. Then we don't have to mix the imjoy_plugin logic into bioimageio.spec and bioimageio collection. I'd say either this clean split or a full integration, but our current mix in-between will not last.

**Comment by FynnBe** [comment]
> Yes, it should be addressed in all the downloaders, and it suppose to be fixed here: https://github.com/bioimage-io/collection-bioimage-io/issues/310#issuecomment-1056710747

I disagree. We now have valid updated RDFs in the gh-pages branch of the collection repo (containing URLs, because relative file paths are all invalid as no data is hosted there). The only way forward I see makes sense is to update the downloader to be able to handle URLs even in these few edge cases we now discovered.
Anything else leads to more problems down the road as we would have invalid RDFs on bioimage.io, which anyone using e.g. bioimageio.spec as a library to load a bioimage RDF (not utilizing the imjoy downloader plugin) would run into as a bug.

**Comment by FynnBe** [comment]
We are moving toward hosting the collection on S3, please reopen if this issue remains
