### ISSUE TITLE
Deploy Preview for collection-bioimage-io failed.

### ISSUE THREAD

**Issue by Zoufu1122** [bioimage-io/archive.bioimage.io#306]
Hello, @esgomezm

      Sorry I don't know much about software issues，can you give some advice how to solve this problem, thanks a lot!
[https://github.com/bioimage-io/collection-bioimage-io/pull/472](url)

**Comment by esgomezm** [comment]
Hi @Zoufu1122 

The link you've sent is broken. Please, could you describe maybe with screenshots, what's your problem when uploading the model?

Thank you!
Esti

**Comment by oeway** [comment]
I think @Zoufu1122 meant this one: https://github.com/bioimage-io/collection-bioimage-io/pull/472

@Zoufu1122 sorry for the confusion, you can ignore the preview error, we disabled that because we need some fix for that. Besides the preview error it seems all the tests passes, we should be able to merge.

**Comment by Zoufu1122** [comment]
Thanks for your attention and reply！ @oeway
So I just wait for the upload and don't need to provide additional information?
May I ask how long this process will take?

**Comment by oeway** [comment]
Hi @Zoufu1122 see here: https://github.com/bioimage-io/collection-bioimage-io/pull/472#issuecomment-1194502486

I will close this issue now, and let's move the discussion there.
