### ISSUE TITLE
The icons in the windows showing the models are inconsistent and confusing

### ISSUE THREAD

**Issue by constantinpape** [bioimage-io/archive.bioimage.io#57]
It's confusing that the top left buttons shows a tool, but is something that offers some preview web service for the model.
As a user one would expect to see the tools that are supported by the model listed; they are currently not there AND can be confused with this button.
I think this should just be a generic "play" button that shows up when hovering over the model
AND we need the list of supported tools that are always visible 

Also, the buttons that show up when hovering over the model are inconsistent (sometimes there is a download button, sometimes not). They should always be the same.

Here is a sketch of some alternative layout for the window (pardon my bad drawing ;)):
![20200707_164925](https://user-images.githubusercontent.com/4263537/86799225-ff94ca00-c071-11ea-818f-4d5db24003e5.jpg)

**Comment by oeway** [comment]
> It's confusing that the top left buttons shows a tool, but is something that offers some preview web service for the model.
> As a user one would expect to see the tools that are supported by the model listed; they are currently not there AND can be confused with this button.

Sorry about the confusion, the current design for these icons are BioEngine Apps which can be a list of model preview service icons, but it's just because the models you see they only have one specified. Add more bioengine apps to `links` of the RDF ([example](https://github.com/bioimage-io/bioimage-io-models/blob/e45d95c95e731b728900949d1e15b536d8562ed2/src/manifest.bioimage.io.yaml#L74-L75)) and you will see more icons. If you want to link to a new software, you need to add it as an application, then add the id of the application to `links` of your model.

> I think this should just be a generic "play" button that shows up when hovering over the model
> AND we need the list of supported tools that are always visible

You should see more tools if you add them to your models, it's just because all our current models support only one tool. We don't have an specific app for a model, so I think a play button won't make much sense. However, we can make a default bioengine app that identified with the play button, but not sure how can we run any models with the default app.
> 
> Also, the buttons that show up when hovering over the model are inconsistent (sometimes there is a download button, sometimes not). They should always be the same.

The hover buttons are shown depending on what available for the current model, some models do not have `git_repo` so there will be no github icon, some do not provide a `download_url`, so no download url. I afraid once the models providers becomes more distributed, or when we upgrade the spec of RDF, inconsistency will always exists. We can either do PR to all the models, or perhaps we can use a badge to list the issues/recommendation for the models, so the authors are motivated to upgrade their model according to our spec.
 
> 
> Here is a sketch of some alternative layout for the window (pardon my bad drawing ;)):

Thanks! so basically you want to move the bioengine apps in the middle row to the right? But I afraid we have two issues here, when you get more icons, it will conflict with the carousel indicator for models with multiple covers, also I have some difficulty to align the items to that position.

**Comment by constantinpape** [comment]
> Sorry about the confusion, the current design for these icons are BioEngine Apps which can be a list of model preview service icons, but it's just because the models you see they only have one specified. Add more bioengine apps to `links` of the RDF ([example](https://github.com/bioimage-io/bioimage-io-models/blob/e45d95c95e731b728900949d1e15b536d8562ed2/src/manifest.bioimage.io.yaml#L74-L75)) and you will see more icons. If you want to link to a new software, you need to add it as an application, then add the id of the application to `links` of your model.

Ok, I see. The problem with the current design is that it's not clear from a user perspective:
- You come to bioimage.io to search for models you can use in a certain tool (= community partner!).
- Currently it's not really obvious which model is suited for which tool (especially because the community partner buttons don't all work, but that's a separate issue).
- Instead, the BioEngineApps are very prominently displayed on top of the models, but a new user would have no idea what they are, because they don't necessarily correspond to the community partner symbols.

In summary: I think tools (=community partners) should be more central to the whole design. BioEngineApps are nice, but they are not the selling point. Also from a contributor point of view: the foremost reason to add a model is to make it available to be used in your tool.
 
> We don't have an specific app for a model, so I think a play button won't make much sense.

Suggestion: just one play button, it opens a menu with the available bio engine apps. If there's no app for this model:
"Sorry we don't have a web-preview tool available" (or something like this).

> The hover buttons are shown depending on what available for the current model, some models do not have `git_repo` so there will be no github icon, some do not provide a `download_url`, so no download url. I afraid once the models providers becomes more distributed, or when we upgrade the spec of RDF, inconsistency will always exists. We can either do PR to all the models, or perhaps we can use a badge to list the issues/recommendation for the models, so the authors are motivated to upgrade their model according to our spec.

I think we should either be more stringent with the yamls in this case and require the fields that are necessary to generate a consistent API. Or we group different things under the same button and then open a small window to select the available options,
e.g. "Download from git" and/or "Download from source" when clicking the "Download" button.

> Thanks! so basically you want to move the bioengine apps in the middle row to the right? But I afraid we have two issues here, when you get more icons, it will conflict with the carousel indicator for models with multiple covers, also I have some difficulty to align the items to that position.

My main point is that these icons should show the community partners that support the model and not BioEngineApps. I think the exact positioning / alignment is not so important for now.

Maybe we need some more discussion on the relation between "Tool" "Community Partner" and "BioEngineApp" before finalising this.

**Comment by oeway** [comment]
> The problem with the current design is that it's not clear from a user perspective:
> 
> You come to bioimage.io to search for models you can use in a certain tool (= community partner!).
> Currently it's not really obvious which model is suited for which tool (especially because the community partner buttons don't all work, but that's a separate issue).
> Instead, the BioEngineApps are very prominently displayed on top of the models, but a new user would have no idea what they are, because they don't necessarily correspond to the community partner symbols.

To clarify, `community partners` are about entities who provide models, not necessary tools. It can be for example, a company or a group who produces several tools. The confusion is mainly because we have only tool logo in the community partners for now. The intended way to "search models by tool" is to go to the "applications" tab, and click the tool card (e.g. Ilastik). With https://github.com/bioimage-io/bioimage.io/pull/64, you will see all the linked models.


The "applications" will contain both tool or BioEngineApp, but this is really implementation details that the user won't even notice. For example, Fiji and Ilastik looks the same under "applications", but the Fiji is implemented with RDF [here](https://github.com/bioimage-io/fiji-bioimage-io/blob/6034c76cda97fd9db48c8c1d6e2e285d1a80136b/manifest.bioimage.io.yaml#L20-L33) and Ilastik is implemented [with BioEngineApp](https://github.com/bioimage-io/bioimage-io-models/blob/aa57c87274a956ef74caf547e95f5834daa92dfd/src/manifest.bioimage.io.yaml#L33-L34). In the case of Ilastik, BioEngine app is just a way to provide a more actionable page with preview function.

The idea is that a contributed software/application can choose to provide two types of source: RDF or BioEngineApp. Either way, the icon will be used as an indicator for whether a model support the software. This will give a consistent definition for applications, and no need to define a specific type of icons for preview app, desktop app, bioengine app, they are show as the software icon. When click a app icon, you can:
 1. show a webpage or markdown page, e.g. the fiji app
 2. if it's an bioengine app, you can render a custom page based on the current context (the selected model), also provide preview. e.g. the Ilastik app

BTW, After https://github.com/bioimage-io/bioimage.io/pull/65, you can click`play` button on [Fiji](https://deploy-preview-66--bioimage.netlify.app/#/?type=application&id=Fiji), and it will show the website. For Ilastik, when we move all ilastik models and its bioengine apps to one of your repo, we can improve the landing page of the Ilastik Preview app, to make sure it shows a general Ilastik page when clicked without a model context.

> Maybe we need some more discussion on the relation between "Tool" "Community Partner" and "BioEngineApp" before finalising this.

Yes, we should!
